version: '3'

env:
  
  lambda_function_name: 
    sh: basename $(dirname $PWD)

tasks:
  run_test_event_1:
    env:
      file_name: email_1.txt
      test_event: test_event_1.json
    cmds:
      # if the test file `email_1.txt` not there in pycon-$USER-nlp-trigger-bkt, run the above command
      # ensure stepfunctions pipeline is not triggered by the above copy 
      # this file is for testing only this lambda
      - echo "Processing {{.TASK}}"
      - aws s3 cp $file_name s3://pycon-$USER-nlp-trigger-bkt
      - sed -e "s|\$USER|$USER|g" template_${test_event} > $test_event
      - |
        (aws lambda invoke \
        --function-name "$lambda_function_name" \
        --invocation-type 'RequestResponse' \
        --payload file://${test_event} \
        output.json && cat output.json | jq) > "output_"{{.TASK}}".json" && \
        cat "output_"{{.TASK}}".json"
      - rm output.json
    silent: false
  
  download_test_event_1:
    env:
      file_name: email_1.txt
    cmds:
      - aws s3 cp s3://pycon-$USER-nlp-intermediary-output-bkt/$file_name output_${file_name}
      - cat output_${file_name}
    silent: false

  run_test_event_2:
    env:
      file_name: email_2.txt
      test_event: test_event_2.json
    cmds:
      # if the test file `email_2.txt` not there in pycon-$USER-nlp-trigger-bkt, run the above command
      # ensure stepfunctions pipeline is not triggered by the above copy
      # this file is for testing only this lambda
      - echo "Processing {{.TASK}}"
      - aws s3 cp $file_name s3://pycon-$USER-nlp-trigger-bkt
      - sed -e "s|\$USER|$USER|g" template_${test_event} > $test_event
      - |
        (aws lambda invoke \
        --function-name "$lambda_function_name" \
        --invocation-type 'RequestResponse' \
        --payload file://${test_event} \
        output.json && cat output.json | jq) > "output_"{{.TASK}}".json" && \
        cat "output_"{{.TASK}}".json"
      - rm output.json
    silent: false
  
  download_test_event_2:
    env:
      file_name: email_2.txt
    cmds:
      - aws s3 cp s3://pycon-$USER-nlp-intermediary-output-bkt/$file_name output_${file_name}
      - cat output_${file_name}
    silent: false